name: Commit validation - Delaguardo flavor
on:
  push:
    branches:
      - main
      - la
jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest] # , windows-latest There is a path issue
        # macOS-latest is removed to save github costs
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.0.1479             # Clojure CLI based on tools.deps
          bb: 1.12.195                  # Babashka
          clj-kondo: 2024.11.14        # Clj-kondo
          cljfmt: 0.13.0               # cljfmt
          zprint: 1.2.9                # zprint
      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: /home/runner/.m2/repository
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-
      - name: Test
        run: bb wf-4 -ibawl -d :common-test
