name: Commit validation - docker flavor
run-name: Test ${{ github.event.head_commit.message }}
on: [push]
jobs:
  run-bb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Base image
        uses: docker://hephaistox/gha-image:1.0.1
